source 'https://rubygems.org'

gem 'rake'
gem 'rack'
gem 'unicorn'
gem 'sinatra'
gem 'haml'
gem 'sass'
gem 'coffee-script'
gem 'execjs'
gem 'therubyracer'
group :development do
  gem 'pry'
  gem 'simplecov'
  gem 'rspec'
  gem 'rack-test'
  gem 'sinatra-contrib', require: 'sinatra/reloader'
  gem 'capistrano'
  gem 'capistrano-rbenv'
  gem 'capistrano-bundler'
  gem 'capistrano3-unicorn'
end
gem 'jubatus'
